# Generated by Django 4.1 on 2022-11-05 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Libreria', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InformacionAdicional',
        ),
    ]
